[build]
  # Comando da eseguire prima della build
  command = "npm install @capacitor/core@6.2.0 @capacitor/haptics@6.0.0 --force"
  # Cartella che Netlify utilizza per pubblicare il sito
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"

[env]
  NODE_VERSION = "18" # Sostituisci con la versione di Node.js che utilizzi
